### ISSUE TITLE
`map-of` specs do not print correctly

### ISSUE THREAD

**Issue by bhb** [jpmonettas/pretty-spec#1]
First, thanks for your work on pretty-spec. It looks great and I am looking forward to using it in Expound!

Repro (`[pretty-spec "0.1.0"]`):

```clojure
(pspec/pprint
   (s/form (s/map-of string? int?)))
```

Expected: `(clojure.spec.alpha/map-of clojure.core/string? clojure.core/int?)`
Actual: `(clojure.spec.alpha/map-of clojure.core/string? )`

**Comment by jpmonettas** [comment]
Hi @bhb , thx for reporting that. 
Just pushed a fix, and released 0.1.1 with the fix.
